name: flowr
description: A modern MIDI chord controller for mobile musicians.
publish_to: 'none'
version: 2.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.9
  sensors_plus: ^4.0.2
  google_fonts: ^6.1.0
  url_launcher: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/Flowr_Icon.png"
  adaptive_icon_background: "#1A1A1A"
  adaptive_icon_foreground: "assets/Flowr_Icon.png"

flutter:
  uses-material-design: true
  
  assets:
    - assets/
    - assets/petal.svg
    - assets/settings.svg
    - assets/midi_connected.svg
    - assets/Flowr_Icon.png
